name = "marketing-report"
compatibility_date = "2024-09-23"
pages_build_output_dir = "dist"

# D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "marketing-report-db"
database_id = "7870ce55-b302-4190-8a68-e07d661e6e93"
